try{
    console.log("x");
}
catch(err){
    console.error(err);
}
finally{
    console.log("this will runs everytime");
}
console.log("reached the end")